### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by pynixwang** [JamitLabs/Accio#52]
```
Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)
Target: x86_64-apple-darwin18.6.0
/Applications/Xcode.app/Contents/Developer/usr/bin/lldb "--repl=-enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -color-diagnostics"
Welcome to Apple Swift version 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.4).
```

```
brew install accio
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

==> Installing accio from jamitlabs/accio
==> Cloning https://github.com/JamitLabs/Accio.git
Updating /Users/pynix/Library/Caches/Homebrew/accio--git
==> Checking out tag 0.6.1
HEAD is now at 6b01bd6 Merge branch 'deploy/0.6.1' into productive
HEAD is now at 6b01bd6 Merge branch 'deploy/0.6.1' into productive
==> make install prefix=/usr/local/Cellar/accio/0.6.1
Last 15 lines from /Users/pynix/Library/Logs/Homebrew/accio/01.make:
Resolving https://github.com/kylef/PathKit at 1.0.0
Cloning https://github.com/onevcat/Rainbow.git
Resolving https://github.com/onevcat/Rainbow.git at 3.1.5
Cloning https://github.com/jakeheis/SwiftCLI.git
Resolving https://github.com/jakeheis/SwiftCLI.git at 5.2.2
Cloning https://github.com/kareman/SwiftShell.git
Resolving https://github.com/kareman/SwiftShell.git at 4.1.2
Cloning https://github.com/Flinesoft/HandySwift.git
Resolving https://github.com/Flinesoft/HandySwift.git at 2.8.0
Cloning https://github.com/kylef/Spectre.git
Resolving https://github.com/kylef/Spectre.git at 0.9.0
Cloning https://github.com/tuist/Shell
Resolving https://github.com/tuist/Shell at 2.0.3
'XcodeProj' /private/tmp/accio-20190528-59953-e4mzwa/.build/checkouts/xcodeproj: error: could not find source files for target(s): XcodeProj; use the 'path' property in the Swift 4 manifest to set a custom target path
make: *** [accio] Error 1

If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
  jamitlabs/accio

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:258:in `raise_api_error': Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}] (GitHub::ValidationFailedError)
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:212:in `open_api'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:357:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:265:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:278:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:374:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:370:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:424:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:141:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:38:in `<main>'
```

**Comment by pynixwang** [comment]
```
mint install JamitLabs/Accio

🌱  Finding latest version of Accio
🌱  Cloning Accio 0.6.1
🌱  Resolving package
🌱  Building package
'XcodeProj' /private/var/folders/hw/q0w4zg512_7472v0hscspx5h0000gn/T/mint/github.com_JamitLabs_Accio/.build/checkouts/xcodeproj: error: could not find source files for target(s): XcodeProj; use the 'path' property in the Swift 4 manifest to set a custom target path
🌱  Encountered error during "swift build -c release -Xswiftc -target -Xswiftc x86_64-apple-macosx10.14". Use --verbose to see full output
🌱  Failed to build Accio 0.6.1 with SPM
```

mint also not work.

**Comment by fredpi** [comment]
Hi @pynixwang, thanks for reporting this 👍

I just tried, but couldn't easily reconstruct these issues on my machine right away. Just to make sure, do you have Xcode 10.2 installed and do the Command Line Tools use it? (The latter can be configured in Xcode Preferences → Locations)

**Comment by Jeehut** [comment]
Is this still happening? Did you check your Swift version (`swift version`), Mint version and Homebrew versions? Also, what version of macOS are you running?
